Import the numpy package under the name np

In [1]:
import numpy as np

Create a null vector of size 10

In [2]:
arr = np.zeros((10))

Create a vector with values ranging from 10 to 49

In [3]:
rng = np.arange(10,49)


Find the shape of previous array in question 3

In [4]:
rng.shape

(39,)

Print the type of the previous array in question 3

In [5]:
rng.dtype

dtype('int32')

Print the numpy version and the configuration

In [6]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/92316/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/92316/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/92316/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

Print the dimension of the array in question 3

In [8]:

print(rng.ndim)

1


Create a boolean array with all the True values

In [9]:
boolean = np.ones((10),dtype=bool)

Create a two dimensional array

In [10]:
twoDim = np.zeros((10,10))
print(twoDim.ndim)

2


Create a three dimensional array

In [11]:
threedim = np.zeros((10,10,10))
print(threedim.ndim)

3


Difficulty Level Easy

Reverse a vector (first element becomes last)

In [12]:
reverse = np.random.randn((10))
print(reverse)
reverse = np.flip(reverse)
print(reverse)

[ 0.6979002   0.34883968 -0.26844415 -0.12920851 -0.52350842 -0.99869316
  0.88856488 -0.82273299 -0.12462864  0.82743104]
[ 0.82743104 -0.12462864 -0.82273299  0.88856488 -0.99869316 -0.52350842
 -0.12920851 -0.26844415  0.34883968  0.6979002 ]


Create a null vector of size 10 but the fifth value which is 1

In [13]:
nullVector = np.array([1 if x == 4 else 0 for x in range(10)])
print(nullVector)

[0 0 0 0 1 0 0 0 0 0]


Create a 3x3 identity matrix

In [14]:
identity = np.identity(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


arr = np.array([1, 2, 3, 4, 5])

Convert the data type of the given array from int to float

In [15]:
arr = np.array([1,2,3,4,5],dtype=float)
arr.dtype

dtype('float64')

arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

Multiply arr1 with arr2

In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

Make an array by comparing both the arrays provided above

In [17]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr3 = arr1 == arr2
print(arr3)

[[False False False]
 [False False False]]



Extract all odd numbers from arr with values(0-9)

In [18]:
odd = np.arange(0,10)
print(odd[odd % 2 != 0])

[1 3 5 7 9]


Replace all odd numbers to -1 from previous array

In [19]:
odd[odd % 2 != 0] = -1
print(odd)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]



arr = np.arange(10)

Replace the values of indexes 5,6,7 and 8 to 12

In [20]:
arr = np.arange(10)
arr[[5,6,7,8]] = 12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


Create a 2d array with 1 on the border and 0 inside

In [21]:
twoD = np.ones((4,4))
twoD[1:-1,1:-1] = 0
print(twoD)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Difficulty Level Medium

arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

Replace the value 5 to 12

In [22]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])
arr2d = np.where(arr2d == 5,12,arr2d)
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

Convert all the values of 1st array to 64

In [23]:
arr3d = np.array([
    [
        [1, 2, 3], 
        [4, 5, 6]
    ], 
    [
        [7, 8, 9], 
        [10, 11, 12]
    ]
])
arr3d[0][0] = 64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [24]:
arr2d = np.arange(0,10).reshape((2,5))
print(arr2d)
arr2d[0]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4])


Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [26]:
arr2d = np.arange(0,10).reshape((2,5))
print(arr2d)
arr2d[1]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([5, 6, 7, 8, 9])

Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [27]:
arr2d = np.arange(0,10).reshape((2,5))
print(arr2d)
arr2d[:,2]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([2, 7])

Create a 10x10 array with random values and find the minimum and maximum values

In [28]:
rand = np.random.randn((100)).reshape((10,10))
print(f"Minimun Value {np.amin(rand)}")
print(f"Maximum Value {np.amax(rand)}")

Minimun Value -2.068162315732941
Maximum Value 2.7127112114913516


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

Find the common items between a and b

In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(f"Common Elements are : {np.intersect1d(a,b)}")

Common Elements are : [2 4]


a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

Find the positions where elements of a and b match

In [30]:
np.searchsorted(a, np.intersect1d(a, b))

array([1, 5], dtype=int64)

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)


Find all the values from array data where the values from array names are not equal to Will

In [31]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
print('==================================================')
print(data[names != 'Will'])

[[ 1.06881845 -0.95612949  0.39106553  0.90538295]
 [-0.73767534  1.72748535 -1.81238182 -1.17379255]
 [-0.59552685  0.161002    0.51147322  1.11055651]
 [-1.05435252 -0.65898589  0.16337427 -0.82507702]
 [-0.24492455 -0.08951381 -1.16874315  0.55860966]
 [ 0.27313172  0.40294478 -1.89513363 -0.43843126]
 [ 1.13577001  0.43500044  0.73546237 -0.34211442]]
[[ 1.06881845 -0.95612949  0.39106553  0.90538295]
 [-0.73767534  1.72748535 -1.81238182 -1.17379255]
 [-1.05435252 -0.65898589  0.16337427 -0.82507702]
 [ 0.27313172  0.40294478 -1.89513363 -0.43843126]
 [ 1.13577001  0.43500044  0.73546237 -0.34211442]]



names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

Find all the values from array data where the values from array names are not equal to Will and Joe

In [32]:
print(data)
print('==================================================')
mask = (names != 'Will') & (names!= 'Joe')
print(data[mask])

[[ 1.06881845 -0.95612949  0.39106553  0.90538295]
 [-0.73767534  1.72748535 -1.81238182 -1.17379255]
 [-0.59552685  0.161002    0.51147322  1.11055651]
 [-1.05435252 -0.65898589  0.16337427 -0.82507702]
 [-0.24492455 -0.08951381 -1.16874315  0.55860966]
 [ 0.27313172  0.40294478 -1.89513363 -0.43843126]
 [ 1.13577001  0.43500044  0.73546237 -0.34211442]]
[[ 1.06881845 -0.95612949  0.39106553  0.90538295]
 [-1.05435252 -0.65898589  0.16337427 -0.82507702]]


Difficulty Level Hard


Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [33]:
rand_arr = np.random.uniform(1,15, size=(5,3))
print(rand_arr)

[[ 4.37636692 10.53374832 12.18225678]
 [ 9.69140239  9.79980569 12.3797554 ]
 [ 5.82115774 11.24107947  9.19379569]
 [13.91676649  6.33629404 14.31400147]
 [ 6.82576913 14.43041932 11.01313207]]


Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [34]:
rand_arr2 = np.random.uniform(1,16, size=(2,2,4))
print(rand_arr2)

[[[ 9.37798711  5.90629621 11.25090696  7.11649266]
  [13.73828269 11.87934743  1.7452644  14.56107322]]

 [[12.97067037 10.486366   14.17570132  7.42877977]
  [ 6.43580832 11.9046477   2.72450647  4.45830163]]]


Swap axes of the array you created in Question 32

In [35]:
print("Original Array")
print(rand_arr2)
print("Swapped Axes")
print(np.swapaxes(rand_arr2, 2, 0))

Original Array
[[[ 9.37798711  5.90629621 11.25090696  7.11649266]
  [13.73828269 11.87934743  1.7452644  14.56107322]]

 [[12.97067037 10.486366   14.17570132  7.42877977]
  [ 6.43580832 11.9046477   2.72450647  4.45830163]]]
Swapped Axes
[[[ 9.37798711 12.97067037]
  [13.73828269  6.43580832]]

 [[ 5.90629621 10.486366  ]
  [11.87934743 11.9046477 ]]

 [[11.25090696 14.17570132]
  [ 1.7452644   2.72450647]]

 [[ 7.11649266  7.42877977]
  [14.56107322  4.45830163]]]


Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [36]:
arr = np.random.uniform(0,20, size=(10))
arr = arr.astype('int32') 
arr =np.sqrt(arr)
arr = np.where(arr < 0.5, 0, arr)
arr = arr.astype('int32')
print(arr)

[1 1 2 4 2 4 3 0 3 4]



Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [37]:
arr = np.random.uniform(0,20, size=(10))
arr1 = np.random.uniform(0,20, size=(10))
newArr = np.maximum(arr,arr1)
print(f"Array 1 : {arr}")
print(f"Array 2 : {arr1}")
print(f"New Array : {newArr}")

Array 1 : [16.31934572 12.92147425 13.58512869 12.17408438  5.76255867  7.16723279
 10.55149926  1.2109301   2.65309965 15.79216665]
Array 2 : [ 2.20964353  4.31176453  4.90492697  8.64913675 12.43898828 17.960058
 11.12612752 19.7773711   9.42179504  8.20648404]
New Array : [16.31934572 12.92147425 13.58512869 12.17408438 12.43898828 17.960058
 11.12612752 19.7773711   9.42179504 15.79216665]


names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

Find the unique names and sort them out!

In [38]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.sort(np.unique(names)))

['Bob' 'Joe' 'Will']


a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])

From array a remove all items present in array b

In [39]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a, b)
print(c)

[1 2 3 4]


Following is the input NumPy array delete column two and insert following new column in its place.

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

In [40]:
sampleArray = np.array([
    [34,43,73],
    [82,22,12],
    [53,94,66]
])
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray, 2, axis=1)
sampleArray = np.insert(sampleArray, 2, newColumn, axis=1)
print(sampleArray)

[[34 43 10]
 [82 22 10]
 [53 94 10]]


x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])

Find the dot product of the above two matrix

In [41]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(np.dot(x,y))

[[ 28.  64.]
 [ 67. 181.]]


Generate a matrix of 20 random values and find its cumulative sum

In [42]:
arr = np.random.uniform(1,20,size=(4,5))
arr = arr.astype('int32')
print(arr.cumsum())

[  5  10  24  35  53  57  67  75  91 105 116 126 134 150 157 174 190 205
 213 219]
