
Numpy_Assignment_2::

Question:1
Convert a 1D array to a 2D array with 2 rows?

Desired output::


array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4 , 5, 6, 7, 8, 9])
arr = arr.reshape((2,5))
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Question:2
How to stack two arrays vertically?

Desired Output::

array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

In [3]:
arr1 = np.array([[0, 1, 2, 3, 4],
                [5, 6, 7, 8, 9]])
arr2 = np.ones((2,5))
arr3 = np.vstack((arr1,arr2))
arr3 = arr3.astype('int32')
print(arr3)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Question:3

How to stack two arrays horizontally?

Desired Output::

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [4]:
arr4 = np.hstack((arr1,arr2))
arr4 = arr4.astype('int32')
print(arr4)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


Question:4¶
    
How to convert an array of arrays into a flat 1d array?

Desired Output::

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr = arr.flatten()
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Question:5
    
How to Convert higher dimension into one dimension?

Desired Output::

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [6]:
arr5 = np.array([
    [ 0, 1, 2],
    [ 3, 4, 5],
    [ 6, 7, 8],
    [ 9, 10, 11],
    [12, 13, 14]
])
arr5 = np.ravel(arr5)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


Question:6
    
Convert one dimension to higher dimension?

Desired Output::

array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]])

In [7]:
arr5.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Question:7
    
Create 5x5 an array and find the square of an array?

In [13]:
arr8 = np.random.randint(1,25, size = (5,5))
print("Original Array: \n")
print (arr6)
print("\n")
print("Square of Array: \n")
print(arr6 ** 2)

Original Array: 

[[24 12 14 18 17]
 [11 10 12 15 14]
 [ 4 19  7 19 12]
 [10 21  2  4 20]
 [ 4 12 16 20 14]]


Square of Array: 

[[576 144 196 324 289]
 [121 100 144 225 196]
 [ 16 361  49 361 144]
 [100 441   4  16 400]
 [ 16 144 256 400 196]]


Question:9
    
Find the standard deviation of the previous array in Q8?

In [14]:
print("Original Array: \n")
print (arr8)
print("\n")
print("Standard deviation of Array: \n")
print(np.std(arr8))

Original Array: 

[[21 20  7  4  3]
 [13  4  4  6 24]
 [14 16 12  5 21]
 [ 1 17 16 14  9]
 [13 24 11  8  7]]


Standard deviation of Array: 

6.736646049778777


Question:10
    
Find the median of the previous array in Q8?

In [15]:
print("Original Array: \n")
print (arr8)
print("\n")
print("Median of Array: \n")
print(np.median(arr8))

Original Array: 

[[21 20  7  4  3]
 [13  4  4  6 24]
 [14 16 12  5 21]
 [ 1 17 16 14  9]
 [13 24 11  8  7]]


Median of Array: 

12.0


Question:11
    
Find the transpose of the previous array in Q8

In [16]:
print("Original Array: \n")
print (arr8)
print("\n")
print("Transpose of Array: \n")
print(np.transpose(arr8))

Original Array: 

[[21 20  7  4  3]
 [13  4  4  6 24]
 [14 16 12  5 21]
 [ 1 17 16 14  9]
 [13 24 11  8  7]]


Transpose of Array: 

[[21 13 14  1 13]
 [20  4 16 17 24]
 [ 7  4 12 16 11]
 [ 4  6  5 14  8]
 [ 3 24 21  9  7]]


Question:12
    
Create a 4x4 an array and find the sum of diagonal elements?

In [17]:
arr7 = np.random.randint(1,20, size = (4,4))
print("Original Array: \n")
print (arr7)
print("\n")
print("Sum of diagonal elements of Array: \n")
print(np.trace(arr7))

Original Array: 

[[ 4  1 12 11]
 [12 17 19 10]
 [ 4  3 14 15]
 [ 1  9 19  5]]


Sum of diagonal elements of Array: 

40


Question:13
    
Find the determinant of the previous array in Q12?

In [13]:

In [18]:
print("Original Array: \n")
print (arr7)
print("\n")
print("Determinant of Array: \n")
print(np.linalg.det(arr7))

Original Array: 

[[ 4  1 12 11]
 [12 17 19 10]
 [ 4  3 14 15]
 [ 1  9 19  5]]


Determinant of Array: 

-6739.999999999995
